[package]
name = "json-2-yaml"
version = "0.1.1"
edition = "2024"
license = "MIT"
description = "cli tool to convert json to yaml"
repository = "github.com/nilsmartel/json-2-yaml"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34"
